name: checks

on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false
      - uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
        with:
          enable-cache: true
      - uses: joerdav/setup-xc@eaed99ccd40453d5ab8fe50e7dfd033e6f302e98 # v1
      - name: "software-versions"
        run: |
          set -x
          uv --version
          xc --version
          node --version
          npm --version
          docker --version
          docker compose version

      - run: xc test
      - run: xc lint
      - run: xc audit

  secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: "secret-scanning"
        uses: trufflesecurity/trufflehog@17456f8c7d042d8c82c9a8ca9e937231f9f42e26 # v3.95.2
        with:
          extra_args: --results=verified,unknown
