name: checks

on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: astral-sh/setup-uv@11f9893b081a58869d3b5fccaea48c9e9e46f990 # v8.3.2
        with:
          enable-cache: true
      - uses: joerdav/setup-xc@eaed99ccd40453d5ab8fe50e7dfd033e6f302e98 # v1
      - name: "software-versions"
        run: |
          set -x
          uv --version
          xc --version
          node --version
          npm --version
          docker --version
          docker compose version

      - run: xc test
      - run: xc lint
      - run: xc audit

  secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: "secret-scanning"
        uses: trufflesecurity/trufflehog@27b0417c16317ca9a472a9a8092acce143b49c55 # v3.95.9
        with:
          extra_args: --results=verified,unknown
